---
title: "Rabbits and Hawks"
author: "Lizzy Schattle and Gabe De La Rosa"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(sensitivity)

# Leslie Matrix

# 4 age groups
nclasses = 4

# create a growth matrix to store fertility and survivability information
gmatrix=matrix(nrow=nclasses, ncol=nclasses)
gmatrix

# change NAs to zero
gmatrix[]=0.0
gmatrix

# assign values for fertility for each of the age classes 
# notes that fertility rates are rabbits/female
fert =  c(0, 2, 6, 1)

# enter into our matrix
 gmatrix[1,]=fert
 
 # now add survivability 
 # survivability (to the next class) is also per time step
gmatrix[2,1]=0.8
gmatrix[3,2]=0.85
gmatrix[4,3]=0.65

# we also want to to account for the oldest population group - they don't transfer to another group
# but they do die - this will be survivability per time step but they just stay in their class/group
gmatrix[4,4]=0.1

gmatrix

```


```{r}
# start with an initial population, lets say 10 adults
p0 = c(0, 0, 10, 0)

# advance to the next time step
p1 = gmatrix %*% p0
p1

# has the total number of individuals changed?
sum(p1)
sum(p0)

# growth rate
sum(p1)/sum(p0)

#add another year
p2 = gmatrix %*% p1



# combined
pop = cbind.data.frame(p0,p1,p2)
pop$age = c("Young","Sub-Adult","Adult","Aged")

popl = pop %>% gather(key="timestep",value="pop",-age)
ggplot(popl, aes(timestep, pop,fill=as.factor(age)))+geom_col(position="dodge")+labs(fill="Age Group")
```


# I think this is where we need to start:

### Run rabbit leslie matrix for 20 years:
```{r multitime}

source("./evolve_pop.R")

# rabbit fertility rates
F1 = 0.0
F2 = 2
F3 = 6
F4 = 1

# survivability 
p1 = 0.8
p2 = 0.85
p3 = 0.65
p4 = 0.1


# initial population parameters
ini = c(0, 0, 10, 0)
nyears = 20
fert = c(F1,F2,F3,F4)
surv = c(p1, p2, p3, p4)
rabbit_pop=evolve_pop(fert, surv, ini, nyears)

head(rabbit_pop)

# graph differnt components of the output
# total population

# add decade 
decade = seq(from=1, to=nyears)
rabbit_tot = cbind.data.frame(decade=decade, poptot=rabbit_pop$poptot)
ggplot(rabbit_tot, aes(decade, poptot))+geom_col()+labs(y="Total Popultation")

# plot information about ages
rabbit_ages = cbind.data.frame(decade=decade, t(rabbit_pop$popbyage))
rabbit_agesl = rabbit_ages %>% gather(key="agecat", value="pop",-decade)
ggplot(rabbit_agesl, aes(decade, pop, fill=agecat))+geom_col()+labs(y="Population", fill="Age Group")


# Pull out the total population at year 20
total_rabbit_y20 <- tail(rabbit_tot$poptot, 1)
# Pull out the young at year 20
total_young_y20 <- rabbit_agesl %>% 
  filter(decade == 20, agecat == 1) %>% 
  select(pop)
```

After 20 years, the rabbit population is `r total_rabbit_y20`. The young population is `r total_young_y20$pop`.

### Rabbit Sensitivity to Hawk Predation:

```{r}
# Run a sobel on young  and sub adult age class survival:
# This is p1 and p2.


# survivability - based on mortality rates per thousand per decade
nsample=200

p1 = 0.8
p2 = 0.85
p3 = 0.65
p4 = 0.1

# create our two samples for Sobel
# first do our survivability
ps1 = cbind.data.frame(p1=runif(min=0.65, max=0.75, n=nsample), 
                       p2 = runif(min=0.75, max=0.8, n=nsample),
                       p3 = p3, 
                       p4 = p4)

ps2 = cbind.data.frame(p1=runif(min=0.65, max=0.75, n=nsample), 
                       p2 = runif(min=0.75, max=0.8, n=nsample),
                       p3 = p3, 
                       p4 = p4)

fs1 = cbind.data.frame(F1 = F1,
                       F2 = F2,
                       F3 = F3,
                       F4 = F4)

totalps1 = cbind.data.frame(ps1, fs1)
totalps2 = cbind.data.frame(ps2, fs1)


sens_rabbit=soboljansen(model = NULL, totalps1, totalps2, nboot = 100)

head(sens_rabbit$x)
nsim=nrow(sens_rabbit$X)

# Input other parameters from above:
ini = c(0, 0, 10, 0)
nyears = 20
fert = c(F1, F2, F3, F4)

# Use wrapper function: this lets us pmap our function over all param combos
p_wrapper = function(p1, p2, p3, p4, F1, F2, F3, F4, use_func, initialpop, nstep){
  fertility = fert
  survivability= c(p1, p2, p3, p4)
  
  res = use_func(survivability =survivability, fertility = fertility, initialpop=initialpop, nstep=nstep)
  # now return the final population total
  return(finalpop=res$poptot[nstep])
}

###
###    Do we need to do a sobel for each individual parameter? Or does doing both of them together work?
###
###

# pmap the wrapper function over the sobel df:

res = as.data.frame(sens_rabbit$X) %>% 
  pmap_dbl(p_wrapper, initialpop=ini, nstep=nyears, use_func=evolve_pop)


ggplot(data.frame(finalpop=res), aes(x=finalpop)) + geom_density()

ggplot(data.frame(finalpop=res), aes(x="", y=finalpop/1000) )+geom_boxplot(fill="blue")+
  theme(axis.title.x = element_blank())+labs(y="Final Pop (in 1000s)")

sens_rabbit=tell(sens_rabbit, res)

# loot at results
sens_rabbit$S
sens_rabbit$T

# graph the most sensitive parameter
tmp = cbind.data.frame(sens_rabbit$X, pop12=sens_rabbit$y)
ggplot(tmp, aes(p1, pop12))+geom_point()+labs(x="Survivability of Young",y="Pop after 20 Years")

#p young
tmp_p1 <- tmp %>%
  mutate(p1 = round(p1, digits = 2)) %>% 
  group_by(p1) %>% 
  summarise(pop = mean(pop12))

#p sub adult
tmp_p2 <- tmp %>%
  mutate(p2 = round(p2, digits = 2)) %>% 
  group_by(p2) %>% 
  summarise(pop = mean(pop12))


```

